name: auto_service_locator
description: A Service Locator that can automatically satisfy dependencies.
version: 0.0.1
repository: https://github.com/feinstein/auto_service_locator
issue_tracker: https://github.com/feinstein/auto_service_locator/issues
topics:
  - service-locator
  - dependency-injection

environment:
  sdk: ^3.9.2

dependencies:
  logging: ^1.3.0
  meta: ^1.17.0

dev_dependencies:
  test: ^1.25.6
